### ISSUE TITLE
METAISSUE: Caracterizar al estado de Yucatán como parte del estudio técnico para la actualización del POETY #FOMIX #ETAPA1

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#14]
## **Objetivo:**
Caracterizar al territorio de la entidad de Yucatán y analizar el patrón de ocupación al que se encuentra sujeto mediante la descripción de los subsistemas que conforman el sistema territorial. 

**NOTA:** Este objetivo es uno de los pasos solicitados que en conjunto con el diagnóstico, pronóstico y la propuesta del POET, formarán el estudio técnico para la actualización del Programa de Ordenamiento Ecológico del Territorio del estado de Yucatán (POETY).

## **Productos a entregar:**
De acuerdo a lo establecido en el Anexo del documento Demanda Específica se obtendrán los siguientes productos, que deben contar con texto, bases de datos y mapas: 

- [x] Subsistema productivo @aleestrada #13 
- [x] Subsistema socioeconómico @ofegarcia #16 
- [x] Subsistema natural @CorinaCantero #7 

Los productos estarán ubicados en: FOMIX\fmx_estudio_tecnico\caracterizacion_subs

## Actividades:

Preparar insumos para utilizar en la caracterización de los subsistemas:

**1. Bases de datos:** 
- Integrar bancos de datos georeferenciables y capas geográficas con base en información oficial #1  Ubicación en Dropbox: SIG\desarrollo\sig_fomix\insumos
- Generar gráficas y bases de datos para el estado de Yucatán #6 
Ubicación en Dropbox: FOMIX\fmx_insumos\fmx_estadisticas2.

**2. Fuentes bibliográficas:**
- Compilar banco de datos documental en Mendeley #2  
Ubicación en Dropbox: FOMIX\fmx_insumos\fmx_mendeley

**3. Mapas temáticos:**
- Generar mapas temáticos con base en términos de referencia para el estado de Yucatán #3, #10 
- Actualizar información de mapas del sistema socioeconómico #12
Ubicación en Dropbox: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes

**Comment by CorinaCantero** [comment]
### Acuerdos reunión 06/03/2020

- No se incluirá en la caracterización las islas del estado de Yucatán (Arrecife Alacranes, Cayo Arenas y Arrecife Triángulos).
- Para los mapas: de "Carreteras y lugares centrales" y "Localidades débilmente integradas" se utilizarán las categorías hechas para el Índice de dispersión poblacional, (localidades cercanas a ciudades y localidades aisladas).
- Se hará la clasificación de las categorías de los mapas de los subsistemas socioeconómico y productivo con weber-fechner (1.5). 

### **Actividades:**
- [ ] Para mapas de cultivos: buscar en bases de datos los cultivos con mayor superficie sembrada/mayor valor de producción.
- [ ] Mapas por AGEB
Crear índices para realizar los mapas:
- [ ]  Mapa analítico de calidad de los recursos (incorporando al menos agua, vegetación y suelo)
- [ ] Mapa de fragilidad del territorio
- [ ] Mapas síntesis de los subsistemas

**Comment by CorinaCantero** [comment]
### AVISO

@paola-gp 
La base de datos con los mapas que tienen unidades cuantitativas está ubicada en: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\relacion_mapas_unidades

**Comment by CorinaCantero** [comment]
### Acuerdos reunión 24/03/2020

Correo enviado por @dpedroza74:

**Mapas aspectos demográficos:**

- Poner en la leyenda del mapa "Cuartil" arriba de los colores
- Los mapas se harán por municipio (señalando la delimitación de las 7  regiones) y por regiones (haciendo un promedio).


**Mapas del subsistema natural:**

- Poner la delimitación de regiones
- Para el mapa de cobertura y uso de suelo actual y de las series anteriores, hacer una  tabla con la cruza municipio/regiones/cobertura para tener filtros, hacer la descripción y tener una serie de tiempo - ver la tabla y cualquier duda con Luis.

**Bases de datos:**

- Las base de datos se irán limpiando conforme se necesiten, por ahora se requiere limpiar únicamente las que se estén usando para el informe. 
- De todos modos se tiene que tener un catálogo completo de todo lo disponible. El formato lo tiene Corina y ella es la responsable de la integración 
- Para construir bancos de datos nuevos, se tienen que seguir los criterios que están en el protocolo. 


Tema | Nombre del   producto | Año | Fuente | Nivel de   desagregación | Metadato | Carpeta en   Dropbox del .csv | Nombre del   archivo .csv | Mapa disponible | Carpeta en   Dropbox del .shp | Nombre del   archivo .shp | Calidad | Notas
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Ubicación en Dropbox: 

**Reuniones de trabajo para resolver temas particulares:**

- Reunión para revisar los requisitos de los bancos de datos y solicitudes de mapas @paola-gp @CorinaCantero  @ofegarcia  @aleestrada 
- @CorinaCantero  se pone de acuerdo con @Rocio97  para rehacer mapas.
- @paola-gp  se pone de acuerdo con @vichdzgeo  para ver plataforma de visualización.

**Comment by dpedroza74** [comment]
**Acuerdos reunión 27/03/2020**

- @aaron-ts Aaron será el responsable de integrar un banco de datos relacional para generar reportes de estadísticas – salidas (gráficas, etc.) para reporte conforme a la plantilla del informe
- Campo común:  municipio y región
- @milocortes Hermilo apoya para interfaz web
- @CorinaCantero Corina (natural), @aleestrada Ale (económico - productivo) y @ofegarcia Ofe (social) entregan bases de datos verificada y con metadatos 
Documentar todo el manejo de la información en issues
- Corina: que Aaron siempre tenga acceso a la ubicación banco de datos finales en el Dropbox y que sepa dónde va a poner los productos
- @paola-gp Paola va a distribuir los lineamientos de las bases de datos – Aaron va a incluir definiciones y comentarios en el transcurso de la mañana.


**Componente natural** 

- Corina: hacer un banco de datos para cada serie de vegetación y usos de suelo por municipio (tipos de vegetación agrupados)
- Aaron: generar intersecciones – ya hay un script que desarrollaron Fidel y Víctor

**Comment by dpedroza74** [comment]
**Acuerdos reunión 27/03/2020**
reunión con Luis

**Descripción a nivel estatal**
- mapa con municipios y delimitación de las 7 regiones – por cuartiles
- gráfica cajas y bigotes
- caracterización considerando zonas urbanas/rurales (CONAPO) utilizando 4 grupos por tamaño de población - @ofegarcia   lo va a revisar para ver si vale la pena incluirla

**Descripción a nivel de las 7 regiones**
- gráfica de cajas y bigotes

Ya no se hace mapa de regiones con promedios

@ofegarcia envía Luis el banco de datos para que él pueda hacer análisis a Tableau

@Nayita ayuda a Ofelia para hacer las gráficas de cajas y bigotes con ggplot y @aleestrada le explica interpretación de las gráficas

Lo que va a hacer en @aaron-ts  es para tener la capacidad para replicar el análisis y visualizar los resultados

**Comment by Nayita** [comment]
@ofegarcia 
Te envío la ruta para que veas las gráficas de cajas y bigotes que se tienen y puedas elegir presentación y la forma de entrega de datos para generar las gráficas. 
Ruta: ORGANIZACION_APC/apc_repositorio_r/gr_boxplot

**Comment by dpedroza74** [comment]
Acuerdos reunión 3/04/2020
Luis, Ale, Ofe y Daniela

@ofelia va a hacer el guion, de acuerdo con la propuesta, para identificar qué variables se van a graficar 
Ya con eso se hacen las gráficas en Tableau y se trabaja en una redacción modelo que se aplique a todas las variables

**Comment by ofegarcia** [comment]
Seguimiento de acuerdo de reunión del 3/04/2020

En atención al acuerdo de elaborar el guión de las variables socioeconómicas a graficar, se envió tabla de Excel. El archivo se encuentra en carpeta de trabajo:  ogarcia/para_graficas_tableau

Aviso @aaron-ts 
***Se actualizó la base de datos bd_munic_1abr y se cambió el nombre***: 
- se cambió el nombre para hacer referencia a la parte socieoconómica, ahora se llama **bd_munic_socioe_6abr**

- se agregó una columna de población ocupada dedicada al sector terciario (p_sec_ter) el cual consiste en la suma de datos de las dos columnas previas (comercio y servicio), pero guardado como valor.

- el archivo se grabó como *.csv (aunque en el proceso el sistema envió mensaje de posible pérdida de datos)

Quedan pendientes los temas de:
- [ ] Tasa de crecimiento poblacional 
- [ ] Población rural/urbana 
- [ ] Asentamientos regulares e irregulares
- [ ] Migración ( tasa de crecimiento social, flujo migratorio, inmigración municipal)
- [ ] Población indígena (está en otra base de datos, ya lista)

**Comment by CorinaCantero** [comment]
### Acuerdos de entregables para informe de caracterización 03/jun/2020
@dpedroza74: integrará el índice del informe integrado con todas las secciones y número de secciones para que se numeren internamente las secciones. 

Favor de reportar cada uno de los productos a entregar y ubicación en dropbox.

#### Bases de datos con metadatos con lineamientos acordado en issue y se actualizarán con base en reunión del 8/junio/2020 con la SDS 

-Citar como anexo electrónico 
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Mapas (proyecto QGis, PDF y metadatos)
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
Faltan mapas de síntesis de cada subsistemas. 
#### Informe 
@Nayita: dará lineamientos sobre la automatización de figuras (gráficas), mapas y tablas. 
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Anexo metodológico
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Scripts de procedimientos 
@vichdzgeo dará especificaciones
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Referencias
@CorinaCantero: creará grupo en cuenta de FOMIX para subir las referencias. 
Se usará Harvard 10th edition. 
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico

**Comment by Nayita** [comment]
### Aviso importante para la elaboración del informe

Como resultado de la capacitación de hoy se informan lo siguiente:

- La plantilla original no tiene espaciado entre párrafos. Sin embargo, para el informe se incorporará el espaciado con las siguientes características: 8 pto de espaciado posterior. 
Para realizar el cambio se tienen dos opciones:

1. Usar las plantillas previamente modificadas que se encuentran en la siguiente ruta:
\FOMIX\fmx_insumos
Archivos: plantilla_informe_corto.docx y plantilla_informe_largo.docx

2. Modificar el _estilo normal_ directamente en el archivo del informe y automáticamente se pondrá el espaciado en los párrafos del documento.

**Instrucciones**

  - Hacer clic derecho en el recuadro "Normal" de los estilos ubicado en el menú de inicio en la parte superior derecha.

  - Al desplegarse el menú, hacer clic en la opción "Modificar..."

  - hacer clic en el botón "Formato"

  - hacer clic en la opción "Párrafo"

  - Cambiar los puntos a 8 en la opción "Espaciado" ---->"Posterior"

  - Hacer clic en aceptar en ambas en ambas ventanas

  - Verificar el cambio en el texto 

- Para citar la fuente de tablas y gráficas, **no** incorporar la cita al título. Poner la fuente con el estilo de "pie de figura" abajo de las tablas y gráficas con alineación izquierda.

**Comment by Nayita** [comment]
### Aviso importante para la elaboración del informe II

Agregar en el título de su informe la numeración que les corresponde. Ejem. 3.1 Subsistema natural.
Si hay una introducción al capítulo utilizar el estilo del subtítulo nivel 1(3.1) para esta introducción. En caso de entrar directamente al contenido del informe, utilizar el subtítulo nivel 2 (3.1.1) y continuar a partir de ahí, con todos los niveles de subtítulos descendentes que sean necesarios.

**Comment by CorinaCantero** [comment]
### AVISO

Los pendientes para la entrega de la parte de caracterización natural se encuentran en el issue #7

**Comment by CorinaCantero** [comment]
### AVISO

Favor de colocar los archivos finales de la caracterización de los subsistemas para la entrega en la carpeta: FOMIX\fmx_estudio_tecnico\entregas

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
