### ISSUE TITLE
METAISSUE: Realizar diagnóstico institucional disponible para la gestión del ordenamiento ecológico #FOMIX #ETAPA1

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#15]
## **Objetivo:**
Elaborar un diagnóstico de recursos y capacidades disponibles para la gestión del ordenamiento ecológico del territorio y de los instrumentos de política de desarrollo sostenible en el estado de Yucatán.

De acuerdo con la demanda específica se deberá presentar un documento que identifique los recursos y capacidades disponibles para la gestión de los instrumentos de política de desarrollo sostenible y ordenamiento territorial en Yucatán. Dicho documento debe incluir al menos:

- En cuanto a los recursos disponibles: analizar la disponibilidad de equipamiento, infraestructura y presupuesto para manejo de información, implementación de mecanismos de gobernanza y elaboración de estudios técnicos.

-  En cuanto a capacidades: se deberán evaluar las competencias técnicas e institucionales de los diferentes actores sociales para participar en procesos de gobernanza colaborativa.

## **Productos a entregar:** 
- [ ] Meta 1.1.1. Análisis FODA. 
- [ ] Meta 1.1.2. Modelación multicriterio BOCR
- [ ] Meta 1.1.3. Análisis de activos de información

Los productos están ubicados en: FOMIX\fmx_diag_insti

## Actividades:

Para el diagnóstico institucional se desarrollaron las siguientes actividades:

**1. Entrevistas:** 
- Generar entrevistas #FOMIX #18
Ubicación en Dropbox: FOMIX\fmx_diag_insti\entrevistas_finales

**2. Encuestas:**
- Elaborar encuestas para el diagnóstico de capacidades institucionales de #FOMIX #4
Ubicación en Dropbox: FOMIX\fmx_diag_insti\encuestas

**3. Análisis FODA:**
- Generar análisis FODA #FOMIX #17
Ubicación en Dropbox: FOMIX\fmx_diag_insti\foda

**4. Modelo BOCR**
- Generar análisis BOCR #9 
Ubicación en Dropbox: FOMIX\fmx_diag_insti\bocr

**5. Análisis de activos de información**
- Identificar los activos de información y evaluarlos  #11 @ofegarcia 
Ubicación en Dropbox:  FOMIX\fmx_diag_insti\activos_informacion
- Revisión de capas geográficas de la bitácora #8  @CorinaCantero 
Ubicación en Dropbox: SIG\desarrollo\sig_fomix\insumos\catalogo_poety

Elaborar diagnóstico de capacidades institucionales  #4

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
